// <auto-generated />
namespace Pims.Persistent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class createSeller : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createSeller));
        
        string IMigrationMetadata.Id
        {
            get { return "202405031518126_createSeller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
